### ISSUE TITLE
Add test data to repo, set up with config

### ISSUE THREAD

**Issue by jflory7** [unicef/aggregate_airport_mobility#10]
# Summary

Default configuration for the project should use test data to simulate results

# Background

AAM is configured to use data sources [not available](https://github.com/unicef/aggregate_airport_mobility/blob/master/config_sample.js) in the repo. There is some test data available, however. If a user clones the repo and follows the instructions provided, they will not be able to run the project successfully.

While we can't always provide real data, we should make the project work as expected for test data. This makes it easy for a user to set up the program and see real results of how the program works.

Additionally, this also enables us to successfully [use CI integration](https://travis-ci.org/jflory7/aggregate_airport_mobility/builds/326996303).

# Details

It's not clear how to set up the repo now with the test data available. To close this issue, I suggest these actions:

1. Come up with consistent place to store test data
2. Update configuration file to point to test data location (update `gitignore` for processed data)
3. Test program against test data from fresh clone

# Outcome

Project becomes easier for others without real data to see and understand how it works, and also makes it easier to set up if the default config works with test data out of the box

**Comment by jflory7** [comment]
@carloscdias I think this issue was fixed in 389c9c8efbd164f9f450d5f48a70a8ac5b9b8903 – can you confirm?

**Comment by carloscdias** [comment]
@jflory7 Yes, it is. Now the project has a valid config_sample.js for the repository that just needs to be copied as config.js to the root directory for the project to run.

**Comment by jflory7** [comment]
@carloscdias Excellent! I'm closing this issue as complete then. 👍
