### ISSUE TITLE
Set description field of repo

### ISSUE THREAD

**Issue by jflory7** [unicef/aggregate_airport_mobility#21]
Let's set the description field of the repo so people will know what this repo is for when scrolling or searching on GitHub.

I suggest the first line of the README: `Aggregate Amadeus mobility data by administrative boundary to produce CSV output`

It requires an admin of the repo to do this. @mikefab can edit it on the [home page](https://github.com/unicef/aggregate_airport_mobility) of the repo.

![Edit the repo description](https://user-images.githubusercontent.com/4721034/34845110-c9703f2e-f6e1-11e7-80cb-80d637629ac9.png)

----

_Tagging unicef/magicbox#4 for tracking._

**Comment by mikefab** [comment]
Great idea, thank you. Done.
